### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by silasb** [ParentSquare/faulty#18]
We're evaluating different libraries for Circuit Breaking and this one caught my interest. Love the documentation effort.

Is this production ready?

Would you accept outside contributions?

Any caveats or things to watch out for when using this library?

**Comment by justinhoward** [comment]
> Is this production ready?

We're using it in production and consider it production-ready, but it is new software and the release version number reflects that.

> Would you accept outside contributions?

Yes. High quality patches that fit with the direction of Faulty are welcomed.

> Any caveats or things to watch out for when using this library?

See current open issues for some issues and considerations. The documentation also has some usage notes that should be considered.
