### ISSUE TITLE
Possible to tune the CircuitProxy internal Circuit?

### ISSUE THREAD

**Issue by silasb** [ParentSquare/faulty#20]
During some experimentation I noticed that if I turn off Redis and turn it back on the internal circuit needs to cool down for 300 seconds, which is the default. 

Ideally this would be something that we should be able to change.  I was hoping that we could modify the default circuit and CircuitProxy would use that but I haven't figured out how.  Is this possible?

**Comment by justinhoward** [comment]
It's not particularly ergonomic, but you can provide your own storage adapter chain during configuration. The equivalent of the default would be this:

```ruby
Faulty.init do |config|
  config.notifier = Faulty::Events::Notifier.new(config.listeners || [])
  config.storage = Faulty::Storage::FaultTolerantProxy.new(
          Faulty::Storage::CircuitProxy.new(
            Faulty::Storage::Redis.new,
            circuit: Faulty::Circuit.new(
              Faulty::Storage::CircuitProxy.name,
              cool_down: 15,
              notifier: config.notifier
            )
          ),
          notifier: config.notifier
  )
end
```

Here I set the `cool_down` to 15 seconds. If you prefer, you could even remove the CircuitProxy from the chain entirely.

**Comment by justinhoward** [comment]
It might also be a good idea to have more conservative defaults for the internal circuit. I'll leave this open to address that.

**Comment by justinhoward** [comment]
I didn't adjust the defaults, but I did merge #22 which improves the syntax to override the default options, so I'll close this for now.
