### ISSUE TITLE
Make patched redis aware of Redis::CommandError due to blocked main loop

### ISSUE THREAD

**Issue by senny** [ParentSquare/faulty#29]
Originated from a follow-up discussion on https://github.com/ParentSquare/faulty/pull/14#issuecomment-853114937

When trying to simulate a downtime in our Heroku hosted Redis instance, I resorted to block the main loop with a LUA script (`DEBUG SLEEP` is not available). While this did block the main loop, it results in `Redis::CommandError` errors being raised. These are currently not considered relevant to trip the circuit.

The exception looks like this:

```
error='Redis::CommandError' 
message="BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE."
```

As a way to reproduce it, an endless loop can be run like so:

```ruby
redis.eval("while true do\nend", [])
```

To restore sanity in Redis one can use (on a new connection):

```ruby
redis.script('KILL')
```

**Comment by justinhoward** [comment]
I've been experimenting with this approach. The technique is to patch the client to introduce a specific error subclass for the condition we want to isolate, then it's straightforward to configure Faulty to capture that error.

I haven't worked out a solution for testing. I'm experimenting with creating a separate thread to induce a Redis busy state then clean it up afterwards, but making that reliable is tricky. Stubbing is an option, but especially for these patches, I'd prefer to do a full integration test. I'm open to ideas.

```diff
diff --git a/lib/faulty/patch/redis.rb b/lib/faulty/patch/redis.rb
index 1b228af..470d319 100644
--- a/lib/faulty/patch/redis.rb
+++ b/lib/faulty/patch/redis.rb
@@ -32,12 +32,18 @@ class Faulty
 
       Patch.define_circuit_errors(self, ::Redis::BaseConnectionError)
 
+      class BusyError < ::Redis::CommandError
+      end
+
       # Patches Redis to add the `:faulty` key
       def initialize(options = {})
         @faulty_circuit = Patch.circuit_from_hash(
           'redis',
           options[:faulty],
-          errors: [::Redis::BaseConnectionError],
+          errors: [
+            ::Redis::BaseConnectionError,
+            BusyError
+          ],
           patched_error_module: Faulty::Patch::Redis
         )
 
@@ -51,7 +57,19 @@ class Faulty
 
       # Reads/writes to redis are protected
       def io(&block)
-        faulty_run { super }
+        faulty_run do
+          begin
+            reply = super
+            if reply.is_a?(::Redis::CommandError)
+              if reply.message =~ /^BUSY/
+                reply = BusyError.new(reply.message)
+              end
+            end
+
+            reply
+          end
+        end
       end
     end
   end

```

**Comment by senny** [comment]
> I haven't worked out a solution for testing. I'm experimenting with creating a separate thread to induce a Redis busy state then clean it up afterwards, but making that reliable is tricky

Yea, I tried some variations of that yesterday but nothing would yield a clean slate always or reproduce the problem always. Not sure where I went wrong, conceptually, that should work.

**Comment by senny** [comment]
Regarding the proposed patch, looks like a neat way to introduce handling for arbitrary errors. I also scanned your PR to introduce a mysql2 patch but I see that you didn't need to handle errors based on messages yet. Looks like a good start to start expanding patches.
