### ISSUE TITLE
redis gem v5 compatibility

### ISSUE THREAD

**Issue by promisedlandt** [ParentSquare/faulty#62]
Hello,

I tried out faulty and found that it has an issue when used with a redis gem version >=5.

The specific error message is "Faulty error while checking client options: undefined method `options' for #<Redis::Client redis://127.0.0.1:6379/0>".

I think it's because in https://github.com/redis/redis-rb/pull/1120 the public interface of `Redis::Client` changed, and `options` was removed.  
The new interface instead has `#read_timeout`, `#connect_timeout`, and `#write_timeout`. No idea about the `ConnectionPool` and the number of reconnection attempts.

Simply changing `check_redis_options!` / `check_pool_options!` to use these new readers would of course break compatibility with redis 4.

Based off of cursory testing, it looks like only the checks are affected, and otherwise `faulty` works. But I haven't spent a lot of time testing this, and at the moment I don't plan to :smiley:

**Comment by justinhoward** [comment]
Thanks for the report! I've reproduced in #63 and will take a look at resolving when I have a chance.

**Comment by justinhoward** [comment]
I've merged #63 which fixes the issues you mentioned. I've not fixed support for the Redis patch, but if you're not using that, it works fine with the Redis storage backend.

**Comment by promisedlandt** [comment]
Thank you, it looks great. And I noticed you just pushed Redis 5 support for the patch, too!
